[features]
seeds = false
skip-lint = false
[programs.localnet]
calculator = "JDeZu9xoJEn8FhgTwbKkvNx2VihmT45eZ9AgyiafzpDc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/professorcodegeek/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait= 1000000